Initalized User Profile page (incomplete user data fetching).
44mira/pahinungod-events pull request #20
Opened 2024-05-28 16:41 UTC by wenyngcar

2024-05-28 20:42 UTC, 44mira requested changes

2024-05-28 20:42 UTC, 44mira commented on hooks/use-get-user-identity.ts
> +    useEffect(() => {
use `useQuery` instead of explicit `useEffect`.

2024-05-28 20:42 UTC, 44mira commented on app/volunteers/dashboard/profile/page.tsx
> +  const user = useGetUserIdentity(); // Get the user data.
use `useQuery` instead of explicit `useEffect`

2024-05-28 20:42 UTC, 44mira commented on app/volunteers/dashboard/profile/page.tsx
> +              {value ? value : "No data available."}
Prefer:
 
```tsx
{ value && "No data available" }
```

2024-05-28 20:42 UTC, 44mira commented on app/volunteers/dashboard/profile/page.tsx
> +          <div key={idx}>
You can just use `key={label}`, as this is more stable in this context.

2024-05-28 20:42 UTC, 44mira commented on app/login_user/page.tsx
> +    login(JSON.stringify(values));
This `login()` function is currently for admin only, to be implemented Google OAuth.

2024-05-28 20:42 UTC, 44mira commented on app/login_user/page.tsx
> +              <FormLabel className="font-semibold">Username</FormLabel>
No need for Credentials login. We will only allow login by Google.

2024-05-29 14:57 UTC, kramnev approved these changes

2024-06-01 09:40 UTC, 44mira approved these changes

2024-06-01 09:40 UTC, merged